# Generated by Django 5.1.15 on 2026-06-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_image', models.ImageField(blank=True, help_text='Hospital building photo for the About Us page', null=True, upload_to='site/')),
                ('hero_tagline', models.CharField(default='Where Care Meets Compassion', help_text='Main tagline shown on the About Us hero section', max_length=300)),
                ('about_story', models.TextField(blank=True, default='', help_text="The 'Our Story' paragraph text")),
                ('vision_statement', models.TextField(blank=True, default='', help_text='The vision quote displayed on Vision & Mission page')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('emergency_phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('working_hours', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
