# Generated by Django 5.1.15 on 2026-06-04 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.BinaryField(verbose_name='Image binary data')),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stored_images',
            },
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.storedimage'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hospital_image',
            field=models.ForeignKey(blank=True, help_text='Hospital building photo for the About Us page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings', to='content.storedimage'),
        ),
    ]
