# Generated by Django 5.1.15 on 2026-06-04 13:29

import django.db.models.deletion
from django.db import migrations, models


def clean_old_photo_field(apps, schema_editor):
    """Set empty string photo fields to NULL before converting to FK."""
    Doctor = apps.get_model('doctors', 'Doctor')
    Doctor.objects.all().update(photo=None)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_storedimage_alter_galleryimage_image_and_more'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        # Clean old photo data before field type conversion
        migrations.RunPython(clean_old_photo_field, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_photos', to='content.storedimage'),
        ),
    ]
